config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  #get 'home/index'
  #root 'home#index'
  root 'contacts#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    #@contact = Contact.new
    @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    #@contact = Contact.new(contact_params)
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not Authorized To Modify This Contact" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id, :website, :street, :city, :state, :zip_code)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "here is something about this app..."
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="field form-group">
    <%= form.text_field :first_name, class:'form-control', placeholder:'First Name' %>
  </div>
  <br>

  <div class="field form-group">
    <%= form.text_field :last_name, class:'form-control', placeholder:'Last Name' %>
  </div>
  <br>

  <div class="field form-group">
    <%= form.text_field :email, class:'form-control', placeholder:'Email' %>
  </div>
  <br>

  <div class="field form-group">
    <%= form.text_field :phone, class:'form-control', placeholder:'Phone' %>
  </div>
  <br>

  <div class="field form-group">
    <%= form.text_field :twitter, class:'form-control', placeholder:'Twitter' %>
  </div>
  <br>


  <div class="field form-group">
    <%= form.text_field :website, class:'form-control', placeholder:'Website' %>
  </div>
  <br>
  
  <div class="field form-group">
    <%= form.text_field :street, class:'form-control', placeholder:'Street' %>
  </div>
  <div class="field form-group">
    <%= form.text_field :city, class:'form-control', placeholder:'City' %>
  </div>
  <div class="field form-group">
    <%= form.text_field :state, class:'form-control', placeholder:'State' %>
  </div>
  <div class="field form-group">
    <%= form.number_field :zip_code, class:'form-control', placeholder:'Zip Code' %>
  </div>
  <br>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :contact_user_id, class:'form-control', value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-dark'  %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact, class:'btn btn-dark' %> |
<%= link_to 'Destroy', @contact, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> |
<%= link_to 'Back', contacts_path, class:'btn btn-dark' %>

app/views/contacts/index.html.erb
<% if user_signed_in? %>
<h1>Contacts</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <% if contact.user == current_user %>
      <tr>
        <td>
        <%= link_to contact.first_name + ' ' + contact.last_name, contact %>
        </td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.twitter %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class:'btn btn-dark' %>
<% else %>
<h1>ContactBook</h1>
<p>An app to store contacts</p>
<% end %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path, class:'btn btn-dark' %>

app/views/contacts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @contact.first_name %> <%= @contact.last_name %>
  </h1>
  <p ><strong>Email: </strong><%= @contact.email %></p>
  <p ><strong>Phone: </strong><%= @contact.phone %></p>
  <p><strong>Twitter: </strong><%= @contact.twitter %></p>

  <p><strong>Website: </strong><%= link_to @contact.website, "http://#{@contact.website}", target: "_blank" %></p>
  <p><strong>Address: </strong><%= @contact.street %>, <%= @contact.city %>, <%= @contact.state %> <%= @contact.zip_code %></p>
  <br>


  <hr class="my-4">
  <p class="lead">
    <%= link_to 'Edit', edit_contact_path(@contact), class:'btn btn-dark' %> |
    <%= link_to 'Destroy', @contact, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> |

    <%= link_to 'Back', contacts_path, class:'btn btn-dark' %>
  </p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'ContactBook', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Contact', new_contact_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:'nav-link' %>
          </li>
        <% end %>
        

        

      </ul>

      <% if user_signed_in? %>
        <span class='navbar-text'>Hello, <%= current_user.email %></span>
      <% end %>
      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<br>
<p>add something</p>
<p><%= @about_me %></p>

app/views/home/index.html.erb
<h1>ContactBook</h1>
<p>An app to store contacts</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>ContactBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    <div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>